# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf876050f27bf3be7400d1d16627f8236a0c58d25f34f15ef0905d14fd16e6b2cf81b42e6050183bb34edc6d9b891b09cb59a91499414db9ebb148d6cf8d50fe

test:
  secret_key_base: 859d2845f849cf673bafc0bf1ee17140f256e1a709eb51e62e2432947b217025015a12eed60ad26938de544f1fd0921a30faac5022edd9c833bd140547caecc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
